### PR TITLE
Fix applying ingresses

### LINKED ISSUE #609: Create/apply not working
Deployed headlamp onto Civo Kubernetes which is based on K3s. 
able to open UI and navigate but on creating it gives an error. 

Screenshot 2022-07-20 at 2 05 45 PM

I used the standard installation steps with ingress
```
kubectl -n kube-system create serviceaccount headlamp-admin                                                             

kubectl create clusterrolebinding headlamp-admin --serviceaccount=kube-system:headlamp-admin --clusterrole=cluster-admi
kubectl apply -f https://raw.githubusercontent.com/kinvolk/headlamp/main/kubernetes-headlamp.yaml

```
ingress
```
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: headlamp
    namespace: kube-system
  spec:
    tls:
    - secretName: headlamp
      hosts:
      - headlamp.3b490ef9-d33c-42b7-a4f5-cd54bdff7c7e.k8s.civo.com
    rules:
    - host: headlamp.3b490ef9-d33c-42b7-a4f5-cd54bdff7c7e.k8s.civo.com
      http:
        paths:
        - backend:
            service:
              name: headlamp
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
```

Screenshot 2022-07-20 at 2 07 29 PM

Anything I am missing?

### PR DESCRIPTION
**Pull request by joaquimrocha**
Testing:
- [ ] Apply any ingress YAML * (notice, there's still an issue when the YAML has no namespace, as no default one is set, so be sure to set it)

* For example the one at #609 .

fixes #609

### CODE REVIEW

File: frontend/src/lib/k8s/cluster.ts [hunk 1]
```diff
@@ -97,6 +97,17 @@ export function makeKubeObject<T extends KubeObjectInterface | KubeEvent>(
...
+      return this.className.toLowerCase() + 's';
+    }
+
+    get pluralName(): string {
+      // In case we need to override the plural name in instances.
+      return this._class().pluralName;
+    }
+
     get listRoute(): string {
       return this.detailsRoute + 's';
```
Comment (illume) [inline frontend/src/lib/k8s/cluster.ts:112]: Should the pluralName be used here too?

Comment (joaquimrocha) [reply frontend/src/lib/k8s/cluster.ts:112]: good point. Maybe it should. I will update.
