### PR TITLE
backend: Fix plugins path on windows

### LINKED ISSUE #458: headlamp-plugin is not copying plugins to the correct location in Windows
## Description

A user has reported that headlamp-plugin is copying the plugins into `C:\Users\MYUSER\AppData\Roaming\Headlamp\Config\plugins` (which has an extra `Config` folder than the path that Headlamp reads plugins from).

## Impact

Headlamp cannot load plugins on Windows.

## Expected behavior

We need to make sure that the functions used to get the config folder are consistent between the backend and the `headlamp-plugin` tool.

### PR DESCRIPTION
**Pull request by illume**
## How to use

build headlamp on windows, then use a headlamp plugin

fixes #458

### CODE REVIEW

File: backend/cmd/plugins.go [hunk 1]
```diff
@@ -29,20 +29,29 @@ func defaultPluginDir() string {
...
+	// https://pkg.go.dev/os#UserConfigDir
 	userConfigDir, err := os.UserConfigDir()
 	if err != nil {
 		log.Printf("error getting user config dir: %s\n", err)
 
 		return pluginDirDefault
 	}
 
-	pluginsConfigDir := path.Join(userConfigDir, "Headlamp", "plugins")
+	pluginsConfigDir := filepath.Join(userConfigDir, "Headlamp", "plugins")
```
Comment (joaquimrocha) [inline backend/cmd/plugins.go:49]: Nit: I usually try to avoid extra memory usage (unless golang is smarter than I think).
So I'd not join the path here until I know we're not on Windows.

**Review by joaquimrocha — APPROVED** [review]
Approved with a nit. I understand this is not HPC code, so feel free to ignore if you prefer.
