### PR TITLE
Fix exceptions in cluster actions

### LINKED ISSUE #73: Handle exceptions when performing cluster actions
When performing cluster actions such as edit/delete/create, apparently the exceptions aren't being handled.
I have fixed this locally but I'm filing this issue to track it as I cannot finish it now.

### PR DESCRIPTION
**Pull request by joaquimrocha**
fixes #73

### CODE REVIEW

File: frontend/src/components/common/EditButton.tsx [hunk 1]
```diff
@@ -20,12 +20,30 @@ export default function EditButton(props: EditButtonProps) {
...
+    }
+  }
+
+  async function updateFunc(newItem: KubeServiceAccount) {
+    try {
+      await item.update(newItem);
+    } catch (err) {
+      setErrorMessage(makeErrorMessage(err));
+      setOpenDialog(true);
+      throw err;
```
Comment (ashu8912) [inline frontend/src/components/common/EditButton.tsx:42]: we are already in the catch block why do you want to throw err from here? 
it will break the app if i am correct

Comment (joaquimrocha) [reply frontend/src/components/common/EditButton.tsx:42]: We catch it here so we show the dialog, etc. then we throw it again so it gets caught and treated in the saga (so it displays a notification). This is usually called error propagation.

Comment (ashu8912) [reply frontend/src/components/common/EditButton.tsx:42]: cool if its caught in the saga than its fine

**Review by ashu8912 — APPROVED** [review]
